version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./moodle-volumes/moodle-dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_USER=$MYSQL_ROOT_USER
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

  moodle:
    image: bitnami/moodle:latest
    ports:
      - 80:8080
      - 443:8443
    environment:
      - MOODLE_USERNAME=$MOODLE_USERNAME
      - MOODLE_PASSWORD=$MOODLE_PASSWORD
      - MOODLE_DATABASE_HOST=mysql
      - MOODLE_DATABASE_PORT=3306
      - MOODLE_DATABASE_USER=$MYSQL_USER
      - MOODLE_DATABASE_PASSWORD=$MYSQL_PASSWORD
      - MOODLE_DATABASE_NAME=$MYSQL_DATABASE
      - MOODLE_DATABASE_TYPE=mysqli
      - PUID=998
      - PGID=100
    volumes:
      - ./moodle-volumes/moodle:/bitnami/moodle
      - ./moodle-volumes/moodledata:/bitnami/moodledata
    depends_on:
      - mysql
    links:
      - mysql:mysql